# Site settings
name: go2world
author: go2world
url: http://jc.go2world.icu/
resume_site: http://go2world.xyz
github: https://github.com/go2world/
baseurl: "/"
description: Actually, less is more!
meta_description:
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: go2world

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761338

